// WedSpace Database Types
// TypeScript types for Supabase database schema

export type UserRole = 'user' | 'vendor' | 'venue_owner' | 'admin';
export type ListingStatus = 'draft' | 'active' | 'inactive' | 'suspended';
export type NegotiationStatus = 'pending' | 'countered' | 'accepted' | 'rejected' | 'expired';
export type BookingStatus = 'pending' | 'confirmed' | 'paid' | 'completed' | 'cancelled';
export type PaymentStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
export type VisitStatus = 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'rescheduled';
export type NotificationType = 'negotiation' | 'booking' | 'payment' | 'visit' | 'system' | 'marketing' | 'chat';
export type EscrowStatus = 'pending' | 'funded' | 'partial_released' | 'released' | 'refunded' | 'disputed' | 'cancelled';
export type EscrowTransactionType = 'deposit' | 'release' | 'refund' | 'commission' | 'adjustment';
export type DisputeStatus = 'open' | 'under_review' | 'resolved' | 'closed';
export type MessageType = 'text' | 'image' | 'document' | 'system';
export type MessageStatus = 'sent' | 'delivered' | 'read';
export type AvailabilityStatus = 'available' | 'booked' | 'blocked' | 'pending';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          is_premium: boolean;
          role: UserRole;
          phone: string | null;
          city: string | null;
          wedding_date: string | null;
          budget_min: number | null;
          budget_max: number | null;
          verified: boolean;
          kyc_status: string;
          response_time_hours: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          is_premium?: boolean;
          role?: UserRole;
          phone?: string | null;
          city?: string | null;
          wedding_date?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          verified?: boolean;
          kyc_status?: string;
          response_time_hours?: number;
        };
        Update: {
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          is_premium?: boolean;
          role?: UserRole;
          phone?: string | null;
          city?: string | null;
          wedding_date?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          verified?: boolean;
          kyc_status?: string;
          response_time_hours?: number;
        };
      };
      listings: {
        Row: {
          id: string;
          owner_id: string;
          listing_type: 'venue' | 'vendor';
          venue_id: string | null;
          vendor_id: string | null;
          title: string;
          description: string | null;
          base_price: number | null;
          price_currency: string;
          city: string;
          state: string;
          verified: boolean;
          status: ListingStatus;
          featured: boolean;
          rating: number;
          review_count: number;
          view_count: number;
          inquiry_count: number;
          booking_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          owner_id: string;
          listing_type: 'venue' | 'vendor';
          venue_id?: string | null;
          vendor_id?: string | null;
          title: string;
          description?: string | null;
          base_price?: number | null;
          price_currency?: string;
          city: string;
          state: string;
          verified?: boolean;
          status?: ListingStatus;
          featured?: boolean;
          rating?: number;
          review_count?: number;
          view_count?: number;
          inquiry_count?: number;
          booking_count?: number;
        };
        Update: {
          title?: string;
          description?: string | null;
          base_price?: number | null;
          verified?: boolean;
          status?: ListingStatus;
          featured?: boolean;
          rating?: number;
          review_count?: number;
          view_count?: number;
          inquiry_count?: number;
          booking_count?: number;
        };
      };
      venues: {
        Row: {
          id: string;
          owner_id: string | null;
          name: string;
          description: string | null;
          address: string;
          city: string;
          state: string;
          country: string;
          lat: number | null;
          lng: number | null;
          capacity_min: number | null;
          capacity_max: number | null;
          price_per_plate: number | null;
          base_price: number | null;
          venue_type: string | null;
          rating: number | null;
          review_count: number;
          verified: boolean;
          status: ListingStatus;
          response_time_hours: number;
          cancellation_policy: string | null;
          advance_booking_days: number;
          images: string[] | null;
          amenities: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          owner_id?: string | null;
          name: string;
          description?: string | null;
          address: string;
          city: string;
          state: string;
          country?: string;
          lat?: number | null;
          lng?: number | null;
          capacity_min?: number | null;
          capacity_max?: number | null;
          price_per_plate?: number | null;
          base_price?: number | null;
          venue_type?: string | null;
          rating?: number | null;
          review_count?: number;
          verified?: boolean;
          status?: ListingStatus;
          response_time_hours?: number;
          cancellation_policy?: string | null;
          advance_booking_days?: number;
          images?: string[] | null;
          amenities?: string[] | null;
        };
        Update: {
          name?: string;
          description?: string | null;
          address?: string;
          city?: string;
          state?: string;
          lat?: number | null;
          lng?: number | null;
          capacity_min?: number | null;
          capacity_max?: number | null;
          price_per_plate?: number | null;
          base_price?: number | null;
          venue_type?: string | null;
          verified?: boolean;
          status?: ListingStatus;
          response_time_hours?: number;
          cancellation_policy?: string | null;
          advance_booking_days?: number;
          images?: string[] | null;
          amenities?: string[] | null;
        };
      };
      vendors: {
        Row: {
          id: string;
          owner_id: string | null;
          name: string;
          category: string;
          description: string | null;
          city: string;
          state: string;
          country: string;
          price_range: string | null;
          rating: number | null;
          review_count: number;
          verified: boolean;
          status: ListingStatus;
          response_time_hours: number;
          portfolio_images: string[] | null;
          services_offered: string[] | null;
          cancellation_policy: string | null;
          images: string[] | null;
          contact_email: string | null;
          contact_phone: string | null;
          website: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          owner_id?: string | null;
          name: string;
          category: string;
          description?: string | null;
          city: string;
          state: string;
          country?: string;
          price_range?: string | null;
          rating?: number | null;
          review_count?: number;
          verified?: boolean;
          status?: ListingStatus;
          response_time_hours?: number;
          portfolio_images?: string[] | null;
          services_offered?: string[] | null;
          cancellation_policy?: string | null;
          images?: string[] | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          website?: string | null;
        };
        Update: {
          name?: string;
          category?: string;
          description?: string | null;
          city?: string;
          state?: string;
          price_range?: string | null;
          verified?: boolean;
          status?: ListingStatus;
          response_time_hours?: number;
          portfolio_images?: string[] | null;
          services_offered?: string[] | null;
          cancellation_policy?: string | null;
          images?: string[] | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          website?: string | null;
        };
      };
      negotiations: {
        Row: {
          id: string;
          listing_id: string;
          user_id: string;
          event_date: string;
          guest_count: number | null;
          initial_price: number;
          current_price: number;
          final_price: number | null;
          status: NegotiationStatus;
          expires_at: string | null;
          history: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          listing_id: string;
          user_id: string;
          event_date: string;
          guest_count?: number | null;
          initial_price: number;
          current_price: number;
          final_price?: number | null;
          status?: NegotiationStatus;
          expires_at?: string | null;
          history?: any;
        };
        Update: {
          current_price?: number;
          final_price?: number | null;
          status?: NegotiationStatus;
          expires_at?: string | null;
          history?: any;
        };
      };
      bookings: {
        Row: {
          id: string;
          user_id: string | null;
          venue_id: string | null;
          vendor_id: string | null;
          listing_id: string | null;
          negotiation_id: string | null;
          booking_date: string;
          event_date: string;
          guest_count: number | null;
          total_amount: number;
          final_price: number | null;
          advance_amount: number | null;
          balance_amount: number | null;
          commission_amount: number;
          status: string;
          booking_status: BookingStatus;
          payment_status: string;
          contract_url: string | null;
          special_requests: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id?: string | null;
          venue_id?: string | null;
          vendor_id?: string | null;
          listing_id?: string | null;
          negotiation_id?: string | null;
          booking_date: string;
          event_date: string;
          guest_count?: number | null;
          total_amount: number;
          final_price?: number | null;
          advance_amount?: number | null;
          balance_amount?: number | null;
          commission_amount: number;
          status?: string;
          booking_status?: BookingStatus;
          payment_status?: string;
          contract_url?: string | null;
          special_requests?: string | null;
        };
        Update: {
          guest_count?: number | null;
          total_amount?: number;
          final_price?: number | null;
          advance_amount?: number | null;
          balance_amount?: number | null;
          status?: string;
          booking_status?: BookingStatus;
          payment_status?: string;
          contract_url?: string | null;
          special_requests?: string | null;
        };
      };
      payments: {
        Row: {
          id: string;
          booking_id: string;
          user_id: string;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          amount: number;
          currency: string;
          status: PaymentStatus;
          payment_method: string | null;
          receipt_url: string | null;
          refund_amount: number;
          refund_reason: string | null;
          metadata: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          booking_id: string;
          user_id: string;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          amount: number;
          currency?: string;
          status?: PaymentStatus;
          payment_method?: string | null;
          receipt_url?: string | null;
          refund_amount?: number;
          refund_reason?: string | null;
          metadata?: any;
        };
        Update: {
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          status?: PaymentStatus;
          payment_method?: string | null;
          receipt_url?: string | null;
          refund_amount?: number;
          refund_reason?: string | null;
          metadata?: any;
        };
      };
      reviews: {
        Row: {
          id: string;
          listing_id: string;
          user_id: string;
          booking_id: string | null;
          rating: number;
          title: string | null;
          content: string | null;
          images: string[] | null;
          is_verified: boolean;
          is_featured: boolean;
          helpful_count: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          listing_id: string;
          user_id: string;
          booking_id?: string | null;
          rating: number;
          title?: string | null;
          content?: string | null;
          images?: string[] | null;
          is_verified?: boolean;
          is_featured?: boolean;
          helpful_count?: number;
          status?: string;
        };
        Update: {
          rating?: number;
          title?: string | null;
          content?: string | null;
          images?: string[] | null;
          is_verified?: boolean;
          is_featured?: boolean;
          helpful_count?: number;
          status?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          listing_id: string;
          collection_name: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          listing_id: string;
          collection_name?: string;
          notes?: string | null;
        };
        Update: {
          collection_name?: string;
          notes?: string | null;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: NotificationType;
          title: string;
          message: string;
          data: any;
          read: boolean;
          email_sent: boolean;
          push_sent: boolean;
          created_at: string;
        };
        Insert: {
          user_id: string;
          type: NotificationType;
          title: string;
          message: string;
          data?: any;
          read?: boolean;
          email_sent?: boolean;
          push_sent?: boolean;
        };
        Update: {
          read?: boolean;
          email_sent?: boolean;
          push_sent?: boolean;
        };
      };
      escrow_accounts: {
        Row: {
          id: string;
          booking_id: string;
          user_id: string;
          vendor_id: string | null;
          total_amount: number;
          advance_amount: number;
          balance_amount: number;
          released_amount: number;
          refunded_amount: number;
          commission_amount: number;
          commission_percentage: number;
          status: EscrowStatus;
          currency: string;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_transfer_id: string | null;
          auto_release_date: string | null;
          manual_release_required: boolean;
          release_approved_by: string | null;
          release_approved_at: string | null;
          notes: string | null;
          metadata: any;
          created_at: string;
          updated_at: string;
          funded_at: string | null;
          released_at: string | null;
        };
        Insert: {
          booking_id: string;
          user_id: string;
          vendor_id?: string | null;
          total_amount: number;
          advance_amount: number;
          balance_amount: number;
          released_amount?: number;
          refunded_amount?: number;
          commission_amount?: number;
          commission_percentage?: number;
          status?: EscrowStatus;
          currency?: string;
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_transfer_id?: string | null;
          auto_release_date?: string | null;
          manual_release_required?: boolean;
          notes?: string | null;
          metadata?: any;
        };
        Update: {
          status?: EscrowStatus;
          released_amount?: number;
          refunded_amount?: number;
          razorpay_payment_id?: string | null;
          razorpay_transfer_id?: string | null;
          release_approved_by?: string | null;
          release_approved_at?: string | null;
          notes?: string | null;
          metadata?: any;
          funded_at?: string | null;
          released_at?: string | null;
        };
      };
      escrow_transactions: {
        Row: {
          id: string;
          escrow_account_id: string;
          transaction_type: EscrowTransactionType;
          amount: number;
          currency: string;
          from_user_id: string | null;
          to_user_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_transfer_id: string | null;
          razorpay_refund_id: string | null;
          gateway_response: any;
          status: string;
          processed_at: string | null;
          failed_at: string | null;
          failure_reason: string | null;
          description: string | null;
          metadata: any;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          escrow_account_id: string;
          transaction_type: EscrowTransactionType;
          amount: number;
          currency?: string;
          from_user_id?: string | null;
          to_user_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_transfer_id?: string | null;
          razorpay_refund_id?: string | null;
          gateway_response?: any;
          status?: string;
          description?: string | null;
          metadata?: any;
          created_by?: string | null;
        };
        Update: {
          status?: string;
          processed_at?: string | null;
          failed_at?: string | null;
          failure_reason?: string | null;
          gateway_response?: any;
        };
      };
      escrow_disputes: {
        Row: {
          id: string;
          escrow_account_id: string;
          booking_id: string;
          raised_by: string;
          dispute_type: string;
          dispute_reason: string;
          dispute_amount: number | null;
          evidence_documents: string[] | null;
          evidence_description: string | null;
          status: DisputeStatus;
          priority: string;
          assigned_to: string | null;
          resolution_notes: string | null;
          resolution_action: string | null;
          resolution_amount: number | null;
          resolved_at: string | null;
          resolved_by: string | null;
          last_response_at: string | null;
          response_count: number;
          metadata: any;
          created_at: string;
          updated_at: string;
          closed_at: string | null;
        };
        Insert: {
          escrow_account_id: string;
          booking_id: string;
          raised_by: string;
          dispute_type: string;
          dispute_reason: string;
          dispute_amount?: number | null;
          evidence_documents?: string[] | null;
          evidence_description?: string | null;
          status?: DisputeStatus;
          priority?: string;
          metadata?: any;
        };
        Update: {
          status?: DisputeStatus;
          assigned_to?: string | null;
          resolution_notes?: string | null;
          resolution_action?: string | null;
          resolution_amount?: number | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          last_response_at?: string | null;
          response_count?: number;
          closed_at?: string | null;
        };
      };
      chat_conversations: {
        Row: {
          id: string;
          listing_id: string | null;
          venue_id: string | null;
          vendor_id: string | null;
          user_id: string;
          vendor_user_id: string | null;
          last_message: string | null;
          last_message_at: string | null;
          unread_count_user: number;
          unread_count_vendor: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          listing_id?: string | null;
          venue_id?: string | null;
          vendor_id?: string | null;
          user_id: string;
          vendor_user_id?: string | null;
          last_message?: string | null;
          last_message_at?: string | null;
          unread_count_user?: number;
          unread_count_vendor?: number;
          status?: string;
        };
        Update: {
          last_message?: string | null;
          last_message_at?: string | null;
          unread_count_user?: number;
          unread_count_vendor?: number;
          status?: string;
        };
      };
      chat_messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          sender_type: 'user' | 'vendor';
          message_type: MessageType;
          content: string;
          attachment_url: string | null;
          attachment_type: string | null;
          status: MessageStatus;
          read_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          conversation_id: string;
          sender_id: string;
          sender_type: 'user' | 'vendor';
          message_type?: MessageType;
          content: string;
          attachment_url?: string | null;
          attachment_type?: string | null;
          status?: MessageStatus;
          read_at?: string | null;
        };
        Update: {
          status?: MessageStatus;
          read_at?: string | null;
        };
      };
      availability_calendar: {
        Row: {
          id: string;
          venue_id: string | null;
          vendor_id: string | null;
          listing_id: string | null;
          date: string;
          time_slot: string | null;
          status: AvailabilityStatus;
          price_override: number | null;
          booking_id: string | null;
          min_guest_count: number | null;
          max_guest_count: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          venue_id?: string | null;
          vendor_id?: string | null;
          listing_id?: string | null;
          date: string;
          time_slot?: string | null;
          status?: AvailabilityStatus;
          price_override?: number | null;
          booking_id?: string | null;
          min_guest_count?: number | null;
          max_guest_count?: number | null;
          notes?: string | null;
        };
        Update: {
          status?: AvailabilityStatus;
          price_override?: number | null;
          booking_id?: string | null;
          notes?: string | null;
        };
      };
      shared_planning_access: {
        Row: {
          id: string;
          user_id: string;
          shared_with_email: string;
          shared_with_user_id: string | null;
          access_level: 'view' | 'edit' | 'admin';
          invitation_status: 'pending' | 'accepted' | 'rejected';
          invitation_token: string | null;
          created_at: string;
          updated_at: string;
          expires_at: string | null;
        };
        Insert: {
          user_id: string;
          shared_with_email: string;
          shared_with_user_id?: string | null;
          access_level?: 'view' | 'edit' | 'admin';
          invitation_status?: 'pending' | 'accepted' | 'rejected';
          invitation_token?: string | null;
          expires_at?: string | null;
        };
        Update: {
          access_level?: 'view' | 'edit' | 'admin';
          invitation_status?: 'pending' | 'accepted' | 'rejected';
          shared_with_user_id?: string | null;
        };
      };
    };
    Functions: {
      search_listings: {
        Args: {
          search_query?: string;
          listing_type_filter?: string;
          city_filter?: string;
          min_price?: number;
          max_price?: number;
          min_rating?: number;
          guest_count_filter?: number;
          date_filter?: string;
          use_ai_sort?: boolean;
          limit_count?: number;
          offset_count?: number;
        };
        Returns: Array<{
          id: string;
          title: string;
          description: string;
          base_price: number;
          city: string;
          rating: number;
          review_count: number;
          verified: boolean;
          featured: boolean;
          listing_type: string;
          ai_score: number;
        }>;
      };
    };
  };
}
