// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhzwmqxhcbiphztzhwrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoendtcXhoY2JpcGh6dHpod3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzA0OTYsImV4cCI6MjA2Mjg0NjQ5Nn0.1BLiqrmDnMQ_in600H8rqktWFSDckwFeAH4PB6tNeaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);